=== DucTran2094/XML-XSD/BT03-xsd.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="student">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="name">
              <xs:complexType>
                  <xs:sequence>
                      <xs:element name="firstname" type="xs:string"/>
                      <xs:element name="lastname" type="xs:string"/>
                  </xs:sequence>
              </xs:complexType>
          </xs:element>
          
          <xs:element name="dob" type="xs:date"/>
          <xs:element name="class" type="xs:string"/>
          
          <xs:element name="info">
              <xs:complexType>
                  <xs:sequence>
                      <xs:element name="gender">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:pattern value="male|female"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:element>
                      
                      <xs:element name="address" type="xs:string"/>
                      
                      <xs:element name="phone">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:minLength value="10"/>
                            <xs:maxLength value="11"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:element>
                      
                  </xs:sequence>
              </xs:complexType>
          </xs:element>
          
        </xs:sequence>
      </xs:complexType>
    </xs:element>
    
</xs:schema>

=== DucTran2094/XML-XSD/BT03-xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<student
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='BT03-xsd.xsd'>
    <name>
        <firstname>Travis</firstname>
        <lastname>Duong</lastname>
    </name>
    <dob>1994-09-20</dob>
    <class>C2104L</class>
    <info>
        <gender>male</gender>
        <address>My house</address>
        <phone>0909123456</phone>
    </info>

</student>
